// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TVOutManager {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("MainViewController")]
	public partial class MainViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_clockLabel;
		
		private MonoTouch.UIKit.UITextView __mt_infoLabel;
		
		private MonoTouch.UIKit.UISwitch __mt_tvSwitch;
		
		private MonoTouch.UIKit.UISwitch __mt_videoSwitch;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("showInfo:")]
		partial void showInfo (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Export("toggleVideoOutput:")]
		partial void toggleVideoOutput (MonoTouch.UIKit.UISwitch sender);

		[MonoTouch.Foundation.Export("toggleSafeMode:")]
		partial void toggleSafeMode (MonoTouch.UIKit.UISwitch sender);

		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("clockLabel")]
		private MonoTouch.UIKit.UILabel clockLabel {
			get {
				this.__mt_clockLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("clockLabel")));
				return this.__mt_clockLabel;
			}
			set {
				this.__mt_clockLabel = value;
				this.SetNativeField("clockLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("infoLabel")]
		private MonoTouch.UIKit.UITextView infoLabel {
			get {
				this.__mt_infoLabel = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("infoLabel")));
				return this.__mt_infoLabel;
			}
			set {
				this.__mt_infoLabel = value;
				this.SetNativeField("infoLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("tvSwitch")]
		private MonoTouch.UIKit.UISwitch tvSwitch {
			get {
				this.__mt_tvSwitch = ((MonoTouch.UIKit.UISwitch)(this.GetNativeField("tvSwitch")));
				return this.__mt_tvSwitch;
			}
			set {
				this.__mt_tvSwitch = value;
				this.SetNativeField("tvSwitch", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("videoSwitch")]
		private MonoTouch.UIKit.UISwitch videoSwitch {
			get {
				this.__mt_videoSwitch = ((MonoTouch.UIKit.UISwitch)(this.GetNativeField("videoSwitch")));
				return this.__mt_videoSwitch;
			}
			set {
				this.__mt_videoSwitch = value;
				this.SetNativeField("videoSwitch", value);
			}
		}
	}
}
